### ISSUE TITLE
Add timeout option for big cluster

### ISSUE THREAD

**Issue by goldyfruit** [blemmenes/radosgw_usage_exporter#12]
Currently I'm not able to collect metrics about the buckets because `requests` timeout after 60 seconds.
```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 10.161.70.100
DEBUG:requests.packages.urllib3.connectionpool:"GET /admin/usage/?format=json&show-summary=False HTTP/1.1" 200 1825654
<Response [200]>
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 10.161.70.100
DEBUG:requests.packages.urllib3.connectionpool:"GET /admin/bucket/?format=json&stats=True HTTP/1.1" 504 None
Request error [504]: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```
I tried to set a timeout but I can't go over 60 seconds like if something else was killing the connection.
```
response = requests.get(url, timeout=300, auth=S3Auth(self.access_key,
                                                     self.secret_key,
                                                     self.host))
```
I have a bit more than 7000 buckets.

**Comment by blemmenes** [comment]
@goldyfruit What is your prometheus scrape_interval and scrape_timeout? It could be prometheus that is not allowing the request to go longer than 60s.

**Comment by blemmenes** [comment]
Hmmm. Ok I'll take a look.

**Comment by blemmenes** [comment]
@goldyfruit can you try this [https://gist.github.com/blemmenes/5fc4a7bfbaf2a17fc566d14a1d607085](https://gist.github.com/blemmenes/5fc4a7bfbaf2a17fc566d14a1d607085) simple script to see if it completes and if so how long it takes?

**Comment by goldyfruit** [comment]
@blemmenes sorry, I didn't see your reply!
Sometime it works and sometime it fails, when it works:
```
real	0m35.973s
user	0m1.068s
sys	0m0.356s
```

When it fails:
```
Traceback (most recent call last):
  File "get_bucket_usage.py", line 45, in <module>
    print json.dumps(response.json(), sort_keys=True, indent=4, separators=(',', ':'))
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 741, in json
    return json.loads(self.text, **kwargs)
  File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

real	1m0.114s
user	0m0.068s
sys	0m0.020s
```

**Comment by goldyfruit** [comment]
I found the bottleneck...

It's related to HAproxy, I'm using a VIP to access the Rados Gateway API but I set a timeout of `60` seconds...

Maybe we could add a note in the the README about this to avoid people to open issue unrelated to this exporter. :smile:

**Comment by blemmenes** [comment]
@goldyfruit That's great! Was it `timeout server`?

I can certainly add something to that regard.

**Comment by goldyfruit** [comment]
@blemmenes Yes it was.

**Comment by blemmenes** [comment]
@goldyfruit how about this a3037b6?

**Comment by goldyfruit** [comment]
@blemmenes What do you mean ?

**Comment by blemmenes** [comment]
Closing as a README comment was added as part of 63ea663
