### ISSUE TITLE
Script fails if a bucket exists which has never contained objects

### ISSUE THREAD

**Issue by zieg8301** [blemmenes/radosgw_usage_exporter#15]
If the script encounters a bucket which has never contained objects, the script fails with: 

```Traceback (most recent call last):
  File "./radosgw_usage_exporter.py", line 324, in <module>
    main()
  File "./radosgw_usage_exporter.py", line 313, in main
    args.host, args.admin_entry, args.access_key, args.secret_key))
  File "/usr/local/lib/python2.7/site-packages/prometheus_client/core.py", line 50, in register
    names = self._get_names(collector)
  File "/usr/local/lib/python2.7/site-packages/prometheus_client/core.py", line 86, in _get_names
    for metric in desc_func():
  File "./radosgw_usage_exporter.py", line 70, in collect
    self._get_bucket_usage(bucket)
  File "./radosgw_usage_exporter.py", line 231, in _get_bucket_usage
    if 'size_actual' in bucket['usage']['rgw.main']:
KeyError: 'rgw.main'
```

Environment:
Ceph version: Luminous 12.2.5

**Comment by zieg8301** [comment]
The bucket it is tripping on appears like this:

```
[root@xxxxxxxxxx ~]# radosgw-admin bucket stats --bucket=bucket2
{
    "bucket": "bucket2",
    "zonegroup": "a65c9afb-3e11-4c74-a371-75f7d1206658",
    "placement_rule": "default-placement",
    "explicit_placement": {
        "data_pool": "",
        "data_extra_pool": "",
        "index_pool": ""
    },
    "id": "393e79c3-6a30-49dc-8807-8753e6305338.221027.4",
    "marker": "393e79c3-6a30-49dc-8807-8753e6305338.221027.4",
    "index_type": "Normal",
    "owner": "xxxxxxxx",
    "ver": "0#1,1#1,2#1,3#1,4#1,5#1,6#1,7#1,8#1,9#1,10#1,11#1,12#1,13#1,14#1,15#1,16#1,17#1,18#1,19#1,20#1,21#1",
    "master_ver": "0#0,1#0,2#0,3#0,4#0,5#0,6#0,7#0,8#0,9#0,10#0,11#0,12#0,13#0,14#0,15#0,16#0,17#0,18#0,19#0,20#0,21#0",
    "mtime": "2019-07-11 15:01:35.496317",
    "max_marker": "0#,1#,2#,3#,4#,5#,6#,7#,8#,9#,10#,11#,12#,13#,14#,15#,16#,17#,18#,19#,20#,21#",
    "usage": {},
    "bucket_quota": {
        "enabled": false,
        "check_on_raw": false,
        "max_size": -1,
        "max_size_kb": 0,
        "max_objects": -1
    }
}
```

The key `rgw_main` doesn't get created until objects are put in the bucket, at least in 12.2.5.

**Comment by k0ste** [comment]
We already handle buckets like this in `_get_bucket_usage`.

```
{
    "bucket": "k0ste2",
    "zonegroup": "e07ca1b2-602a-46e5-b2b9-1c4ceda0fb1a",
    "placement_rule": "default-placement",
    "explicit_placement": {
        "data_pool": "",
        "data_extra_pool": "",
        "index_pool": ""
    },
    "id": "f9e6d5e1-208a-4bf2-961f-d747a652b2f8.356128592.2",
    "marker": "f9e6d5e1-208a-4bf2-961f-d747a652b2f8.356128592.2",
    "index_type": "Normal",
    "owner": "k0ste",
    "ver": "0#1",
    "master_ver": "0#0",
    "mtime": "2019-07-15 14:31:02.143656",
    "max_marker": "0#",
    "usage": {},
    "bucket_quota": {
        "enabled": false,
        "check_on_raw": false,
        "max_size": -1,
        "max_size_kb": 0,
        "max_objects": -1
    }
}
```

And returns zero's if bucket is empty.

**Comment by zieg8301** [comment]
_get_bucket_usage first checks for the key "bucket['usage']" (which appears to always exist), and then looks for a value for the key "bucket['usage']['rgw.main']['size_actual']". It assumes that the key "bucket['usage']['rgw.main']" exists, which in some cases it does not.

**Comment by k0ste** [comment]
> _get_bucket_usage first checks for the key "bucket['usage']" (which appears to always exist), and then looks for a value for the key "bucket['usage']['rgw.main']['size_actual']". 

Actually "and then" performs check that key `size_actual` is present in `bucket['usage']['rgw.main']` which is not present in your json.

**Comment by zieg8301** [comment]
Correct, it checks that `size_actual` is present. Regardless, it assumes `bucket['usage']['rgw.main']` is present. You are correct, it is not present in my json, nor is it present in your example. So you're telling me that the code works as-is for yours?

**Comment by k0ste** [comment]
> So you're telling me that the code works as-is for yours?

Exactly. May be you use some old version of exporter or it's specific behavior of 12.2.5 - I don't know. On 12.2.12 I can't reproduce this issue.

**Comment by zieg8301** [comment]
I'm using the latest image from Dockerhub. As this appears to be a fairly basic grass-roots effort, I won't expect support for various versions of Ceph. I guess we will just use our own fork. Thanks.

**Comment by blemmenes** [comment]
@zieg8301 Thanks for reporting the issue. Like @k0ste I don't see this issue in 12.2.11, I'll spin up a test cluster on 12.2.5 and see if I can recreate this.

That said if there are corner cases where that key doesn't exist I don't see a reason to not address it within the exporter.

**Comment by blemmenes** [comment]
So I'm not able to recreate this with a 12.2.5 test cluster. I'm using the blemmenes/radosgw_usage_exporter docker image.

I spun up a test cluster using `cn`, created a bucket called `test-bucket`, pulled usage and as you can see in the json there are no objects (hence no rgw.main key), I then added a single object which you can see in the next output.

When running the exporter against the cluster when there is just a single empty bucket I do not get a crash in the exporter. I've attached both the exporter output and JSON for both an empty bucket and with one object, as well a a screenshot of the test setup.

[emtpy bucket.txt](https://github.com/blemmenes/radosgw_usage_exporter/files/3403635/emtpy.bucket.txt)
[one object.txt](https://github.com/blemmenes/radosgw_usage_exporter/files/3403634/one.object.txt)
![screenshot](https://user-images.githubusercontent.com/1464038/61407429-b5886680-a8ab-11e9-912b-9395962da8b2.png)

Nothing is jumping to mind as to why your setup behaves any different.

**Comment by zieg8301** [comment]
Ok, thanks for trying. I'll see if I can figure out which bucket in our env is causing the error, it might be something else. We also have tenants in play, among other specific configurations. Based on your findings it doesn't appear to be a vanilla 12.2.5 thing. I'll come back with what I find out.

**Comment by blemmenes** [comment]
Hrm... yeah I have not done any testing with tenants so I'm not sure how that changes the json output. Could you provide a sanitized sample of the JSON with a tenant?

**Comment by zieg8301** [comment]
Ok, this is interesting: When running `radosgw-admin bucket stats` I get the following error returned along with the array of bucket jsons:

```2019-07-17 15:17:29.333019 7fc460503c80 -1 ERROR: get_bucket_instance_from_oid failed: -2```

So there is likely something else going on with my cluster that I need to address. To address your question, here is a sample of the JSON on a bucket in a tenant. It doesn't appear to actually be any different:

```    {
        "bucket": "bucket",
        "zonegroup": "31bdc7f7-394d-4e0f-88e9-edcd73099b97",
        "placement_rule": "default-placement",
        "explicit_placement": {
            "data_pool": "",
            "data_extra_pool": "",
            "index_pool": ""
        },
        "id": "f1d0bdb0-5b73-4a0d-9246-9b1618ad625a.666711.1",
        "marker": "f1d0bdb0-5b73-4a0d-9246-9b1618ad625a.666711.1",
        "index_type": "Normal",
        "owner": "tenant$user",
        "ver": "0#1",
        "master_ver": "0#0",
        "mtime": "2018-10-05 10:13:06.321906",
        "max_marker": "0#",
        "usage": {},
        "bucket_quota": {
            "enabled": false,
            "check_on_raw": false,
            "max_size": -1,
            "max_size_kb": 0,
            "max_objects": -1
        }
    }```

**Comment by blemmenes** [comment]
Yeah I just did a quick test and it looks like the only thing that it does is prepend the tenant space separated by a $.

Yeah I've not seen that one before.

**Comment by blemmenes** [comment]
I had bucket index resharding issues on luminous prior to 12.2.11 but I don't recall them affecting bucket stats.

**Comment by zieg8301** [comment]
Sure. I would be fine closing this issue (and related PR) given this seems more specific to my cluster than a Ceph version or feature idiosyncrasy.

**Comment by greatbn** [comment]
@zieg8301  How did you resolve your problem?

**Comment by zieg8301** [comment]
@greatbn I know this is very late, but I just added a try/except in our fork of the code to handle the missing key.
