### ISSUE TITLE
Is bucket quota data collected?

### ISSUE THREAD

**Issue by yxiaoy6** [blemmenes/radosgw_usage_exporter#30]
![image](https://user-images.githubusercontent.com/43592152/142563320-a94fdae3-f8a4-4bb1-9d3a-0cb8e2ead2a2.png)
![image](https://user-images.githubusercontent.com/43592152/142563515-aee3a501-fc96-4524-9661-58fade967aa2.png)

**Comment by k0ste** [comment]
Bucket quota placed in bucket_quota_max_size_bytes metric

**Comment by yxiaoy6** [comment]
> Bucket quota placed in bucket_quota_max_size_bytes metric

![image](https://user-images.githubusercontent.com/43592152/142583873-762f4f65-08a7-42d0-97d6-c0f17a43458f.png)
no this metrics

**Comment by k0ste** [comment]
What is your Ceph version?

**Comment by yxiaoy6** [comment]
> What is your Ceph version?

14.2.10 nautilus

**Comment by k0ste** [comment]
I was double checked on Nautilus 14.2.22. Bucket quota for bytes and objects is present
```python
√ ~ % curl -Ss http://mon.opentech.local:8066/metrics | grep k0ste-quota
radosgw_usage_bucket_quota_enabled{bucket="k0ste-quota",cluster="ceph",owner="k0ste",zonegroup="e07ca1b2-602a-46e5-b2b9-1c4ceda0fb1a"} 1.0
radosgw_usage_bucket_objects{bucket="k0ste-quota",cluster="ceph",owner="k0ste",zonegroup="e07ca1b2-602a-46e5-b2b9-1c4ceda0fb1a"} 0.0
radosgw_usage_bucket_bytes{bucket="k0ste-quota",cluster="ceph",owner="k0ste",zonegroup="e07ca1b2-602a-46e5-b2b9-1c4ceda0fb1a"} 0.0
radosgw_usage_bucket_utilized_bytes{bucket="k0ste-quota",cluster="ceph",owner="k0ste",zonegroup="e07ca1b2-602a-46e5-b2b9-1c4ceda0fb1a"} 0.0
radosgw_usage_ops_total{bucket="k0ste-quota",category="create_bucket",cluster="ceph",owner="k0ste"} 1.0
radosgw_usage_successful_ops_total{bucket="k0ste-quota",category="create_bucket",cluster="ceph",owner="k0ste"} 1.0
radosgw_usage_sent_bytes_total{bucket="k0ste-quota",category="create_bucket",cluster="ceph",owner="k0ste"} 0.0
radosgw_usage_bucket_quota_size_bytes{bucket="k0ste-quota",cluster="ceph",owner="k0ste",zonegroup="e07ca1b2-602a-46e5-b2b9-1c4ceda0fb1a"} 1024.0
radosgw_usage_bucket_quota_size{bucket="k0ste-quota",cluster="ceph",owner="k0ste",zonegroup="e07ca1b2-602a-46e5-b2b9-1c4ceda0fb1a"} 1024.0
radosgw_usage_received_bytes_total{bucket="k0ste-quota",category="create_bucket",cluster="ceph",owner="k0ste"} 0.0
radosgw_usage_bucket_quota_size_objects{bucket="k0ste-quota",cluster="ceph",owner="k0ste",zonegroup="e07ca1b2-602a-46e5-b2b9-1c4ceda0fb1a"} 512.0
```

**Comment by yxiaoy6** [comment]
> I was double checked on Nautilus 14.2.22. Bucket quota for bytes and objects is present
> 
> ```json
> {
>     "bucket": "k0ste-quota",
>     "num_shards": 0,
>     "tenant": "",
>     "zonegroup": "e07ca1b2-602a-46e5-b2b9-1c4ceda0fb1a",
>     "placement_rule": "default-placement",
>     "explicit_placement": {
>         "data_pool": "",
>         "data_extra_pool": "",
>         "index_pool": ""
>     },
>     "id": "f9e6d5e1-208a-4bf2-961f-d747a652b2f8.1132580185.1",
>     "marker": "f9e6d5e1-208a-4bf2-961f-d747a652b2f8.1132580185.1",
>     "index_type": "Normal",
>     "owner": "k0ste",
>     "ver": "0#1",
>     "master_ver": "0#0",
>     "mtime": "2021-11-19 07:56:27.291001Z",
>     "max_marker": "0#",
>     "usage": {},
>     "bucket_quota": {
>         "enabled": true,
>         "check_on_raw": false,
>         "max_size": 1024,
>         "max_size_kb": 1,
>         "max_objects": 512
>     }
> }
> ```
> 
> ```python
> √ ~ % curl -Ss http://127.0.0.1:9242/metrics | grep k0ste-quota
> radosgw_usage_bucket_quota_enabled{bucket="k0ste-quota",cluster="ceph",owner="k0ste",zonegroup="e07ca1b2-602a-46e5-b2b9-1c4ceda0fb1a"} 1.0
> radosgw_usage_bucket_objects{bucket="k0ste-quota",cluster="ceph",owner="k0ste",zonegroup="e07ca1b2-602a-46e5-b2b9-1c4ceda0fb1a"} 0.0
> radosgw_usage_bucket_bytes{bucket="k0ste-quota",cluster="ceph",owner="k0ste",zonegroup="e07ca1b2-602a-46e5-b2b9-1c4ceda0fb1a"} 0.0
> radosgw_usage_bucket_utilized_bytes{bucket="k0ste-quota",cluster="ceph",owner="k0ste",zonegroup="e07ca1b2-602a-46e5-b2b9-1c4ceda0fb1a"} 0.0
> radosgw_usage_ops_total{bucket="k0ste-quota",category="create_bucket",cluster="ceph",owner="k0ste"} 1.0
> radosgw_usage_successful_ops_total{bucket="k0ste-quota",category="create_bucket",cluster="ceph",owner="k0ste"} 1.0
> radosgw_usage_sent_bytes_total{bucket="k0ste-quota",category="create_bucket",cluster="ceph",owner="k0ste"} 0.0
> radosgw_usage_bucket_quota_size_bytes{bucket="k0ste-quota",cluster="ceph",owner="k0ste",zonegroup="e07ca1b2-602a-46e5-b2b9-1c4ceda0fb1a"} 1024.0
> radosgw_usage_bucket_quota_size{bucket="k0ste-quota",cluster="ceph",owner="k0ste",zonegroup="e07ca1b2-602a-46e5-b2b9-1c4ceda0fb1a"} 1024.0
> radosgw_usage_received_bytes_total{bucket="k0ste-quota",category="create_bucket",cluster="ceph",owner="k0ste"} 0.0
> radosgw_usage_bucket_quota_size_objects{bucket="k0ste-quota",cluster="ceph",owner="k0ste",zonegroup="e07ca1b2-602a-46e5-b2b9-1c4ceda0fb1a"} 512.0
> ```

I set the quota using：
radosgw-admin quota set --uid=<uid> --quota-scope=bucket [--max-objects=<num objects>] [--max-size=<max size>]
Can you tell me your method？

**Comment by k0ste** [comment]
```shell
radosgw-admin quota set --quota-scope=bucket --bucket=k0ste-quota --max_size="1024" --max_objects="512"
radosgw-admin quota enable --quota-scope=bucket --bucket=k0ste-quota
```

**Comment by yxiaoy6** [comment]
> ```shell
> radosgw-admin quota set --quota-scope=bucket --bucket=k0ste-quota --max_size="1024" --max_objects="512"
> radosgw-admin quota enable --quota-scope=bucket --bucket=k0ste-quota
> ```

Thank you very much, I will try
