### ISSUE TITLE
Radosgw didn't show usage.

### ISSUE THREAD

**Issue by TeerasakTorugsa** [blemmenes/radosgw_usage_exporter#5]
Hello...

   Firstly, I'm new and I use Ceph Luminous version. When I use radosgw_usage_exporter, my result show something like this

<img width="701" alt="screen shot 2561-04-26 at 1 08 43 pm" src="https://user-images.githubusercontent.com/38744573/39288652-0d0fb5a2-4953-11e8-82e7-173992ba3fdd.png">

my user have both usage= read and buckets=read capabilities

I didn't get any radosgw_usage from my environment. I enable "rgw enable usage log = true" to ceph.conf. Could you please suggest me how to show it.
I'm so sorry, my English so very poor 

Thank you :)

**Comment by blemmenes** [comment]
@TeerasakTorugsa And have you generated traffic to a RGW that has the usage logging enabled?

Thanks,
Berant

**Comment by TeerasakTorugsa** [comment]
@blemmenes Oh! That my fault, I use radosgw's port 8080 instead of 80 so I  change my port to 80 and it's work!

Thank you :)

**Comment by blemmenes** [comment]
Sounds good!
