### ISSUE TITLE
Incorrect data exported for Luminous

### ISSUE THREAD

**Issue by alexey-dushechkin** [blemmenes/radosgw_usage_exporter#6]
Hello,

We're using Luminous 12.2.5 (running for some time with production load), Prometheus 2.3.1.

Exporter duplicates metrics for buckets, but not their vaules, for example:
`radosgw_usage_sent_bytes_total{bucket="bucket1",category="get_obj",owner="user1"} 2024694272.0
radosgw_usage_sent_bytes_total{bucket="bucket1",category="get_obj",owner="user1"} 561271175.0
radosgw_usage_sent_bytes_total{bucket="bucket1",category="get_obj",owner="user1"} 899567901.0`

Total 92 thousand metrics with only around 9 thousand unique ones. Prometheus takes into account only the first metric value, so exporter effectively isn't working.

My guess it's because stats in Luminous is stored and returned in multiple parts, split by various intervals depending on user activity (I have 3 records since 2018-05-17 for user with low-activity bucket and 57 records since 2018-06-18 for user with high activity bucket, and that's per bucket).

**Comment by blemmenes** [comment]
Hmmm. I don't have a production luminous cluster so I was just spinning up
a test cluster from scratch in a container. That may explain why I haven't
seen this.

I'll see what I can do to re-create.

On Thu, Jun 28, 2018 at 8:52 AM, Alexey Dushechkin <notifications@github.com

**Comment by alexey-dushechkin** [comment]
There is another issue related to this one. `radosgw-admin usage show` returns 11 MB of JSON, 13556 "entries" of statistics. Exporter takes approximately 1 second to calculate radosgw_usage_bucket_total, and another 3-3.5 seconds to calculate the rest. I made a dirty patch so statistics queried just for the hour maximum:

```
+        # limit time for stats
+        start_time = time.strftime("%Y-%m-%d %H:00:00", time.gmtime())
+
         # setup empty prometheus metrics
         self._setup_empty_prometheus_metrics()

-        rgw_usage = self._request_data(query='usage', args='show-summary=False')
+        rgw_usage = self._request_data(query='usage', args='show-summary=False&start=' + start_time)
```

The drawback shows itself at the beginning of the hour: my scrape_interval is 15 seconds, and default stat sync period in RGW is 30 seconds, so for some time there are literally no metrics about operations. But instead I got 300 ms instead of 3s for bucket operations count retrieval.

**Comment by blemmenes** [comment]
@alexey-dushechkin Does it seem like an unbounded 'usage show' is showing all these segments back to the last time usage was cleared?

Do any of the past segments change over time or is all current usage put into the most recent segment?

**Comment by alexey-dushechkin** [comment]
1. Usage was never cleared (it's a young cluster), so yes.

2. I spotted one bucket with changes in "past" segments (both increase and decrease in counters, change in "epoch"/"time" fields), and I can't explain it. Most other buckets have changes only in last segments.

**Comment by blemmenes** [comment]
That's interesting that you see previous segments change. 

Just to have an idea of if/how your environment is similar to ours, are your RGW nodes behind a loadbalancer and if so what distribution method are you using (round-robin, least connections, etc)

**Comment by blemmenes** [comment]
Some more thoughts.

1) If you could capture JSON output from ```radosgw-admin usage show --uid=xxx``` where previous segments change that would be really helpful.

2) Also, what is your rgw usage config? Mine is the "default" at least as of jewel:

rgw usage log tick interval = 30
rgw usage log flush threshold = 1024
rgw usage max shards = 32
rgw usage max user shards = 1

**Comment by k0ste** [comment]
> We're using Luminous 12.2.5 (running for some time with production load), Prometheus 2.3.1.
> Exporter duplicates metrics for buckets, but not their vaules, for example:
`
radosgw_usage_sent_bytes_total{bucket="bucket1",category="get_obj",owner="user1"} 2024694272.0 radosgw_usage_sent_bytes_total{bucket="bucket1",category="get_obj",owner="user1"} 561271175.0 radosgw_usage_sent_bytes_total{bucket="bucket1",category="get_obj",owner="user1"} 899567901.0
`

We need test data to determine how this possible.
I use exporter with 12.2.5 and metrics are correct:

```shell
[k0ste@WorkStation ~]$ curl http://localhost:9242 | grep wal_g | grep radosgw_usage_sent_bytes_total | grep get_obj
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  165k    0  165k    0     0   708k      0 --:--:-- --:--:-- --:--:--  708k
radosgw_usage_sent_bytes_total{bucket="-",category="get_obj",owner="wal_g"} 38621.0
radosgw_usage_sent_bytes_total{bucket="postgres-database-backups-wal-e",category="get_obj",owner="wal_g"} 6593376589277.0
radosgw_usage_sent_bytes_total{bucket="postgres-database-backups-wal-g",category="get_obj",owner="wal_g"} 1025841619363.0
radosgw_usage_sent_bytes_total{bucket="wal-e-test",category="get_obj",owner="wal_g"} 72833943.0
radosgw_usage_sent_bytes_total{bucket="walshipping-bucket-test",category="get_obj",owner="wal_g"} 436729792.0
radosgw_usage_sent_bytes_total{bucket="postgres-database-backups-wal-e",category="get_obj",owner="wal_g"} 9698.0
```

**Comment by blemmenes** [comment]
So I've confirmed that this behavior is expected and is not limited to just luminous (I see it in our jewel clusters). How quickly this issues appears is dependent on the volume of opperations for a given UID, and that could be why some people don't see it yet (or they trim their usage regularly).

Essentially data is flushed from the RGW nodes to the OSD backend (based on the values of rgw_usage_log_flush_threshold and rgw_usage_log_tick_interval) and when that data is retrieved by the client (either the admin ops API that this collector uses, or the radosgw-admin CLI tool), the backend delivers it in batches of 1000 entries.

This is why there could be multiple "duplicate" entries for a given bucket, if there are more than 1000 usage entries there will be multiple responses. With all new updates going into the most recent batch of 1000. The older entries being static.

I'll be modifying the exporter to detect when this is occurring and sum together the values to report correct values.

**Comment by blemmenes** [comment]
I finally got time to circle back around and resolve this. I'm running the `wip-fix-truncated` branch in production right now and it seems to be reporting correctly for our high transaction users.

Assuming it continues to behave well I'll do a PR to master in the next couple of days.

**Comment by k0ste** [comment]
@alexey-dushechkin, can you test `wip-fix-truncated` branch?
Thanks.

**Comment by blemmenes** [comment]
@k0ste @alexey-dushechkin `wip-fix-truncated` has been running fine for me, I'm going to merge this in.
