### ISSUE TITLE
Missing usage capability to user.

### ISSUE THREAD

**Issue by goldyfruit** [blemmenes/radosgw_usage_exporter#9]
Hi,

Without `usage=read` capability I'm not able to retrieve all the metrics, I got this error with `docker logs`
```
Request error [403]: {"Code":"AccessDenied","RequestId":"tx000000000000000000090-005b887ffb-1c6c37f-gateway","HostId":"1c6c37f-gateway-gateway"}
```
I'm running Luminous 12.2.7.

**Comment by blemmenes** [comment]
Yeah that's as expected. Also noted in the README is that the user needs ```buckets=read``` in order to gather bucket level metrics.

**Comment by goldyfruit** [comment]
Damn, my bad. :)
